#!/usr/bin/env python3
"""Render a validated profile.json into paste-friendly profile.md and a skill package.

profile.md can be pasted into any AI tool. The generated skill package can be
installed into Codex-style skill directories.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path


CONF_BADGE = {
    "high": "🟢 high",
    "medium": "🟡 medium",
    "low": "🟠 low",
    "unstable": "⚪ unstable",
}


def build_profile_md(profile: dict) -> str:
    """Build the clean user-facing context file intended for direct AI use."""
    axioms = profile.get("axioms", [])
    lines: list[str] = []
    lines.append("# Personal AI Collaboration Context\n\n")
    lines.append(
        "Use this context to adapt your collaboration style for this user. "
        "These are working rules distilled from the user's prior AI interactions.\n\n"
    )
    lines.append("## How To Use This\n\n")
    lines.append("- Apply these rules when planning, answering, reviewing, or implementing for this user.\n")
    lines.append("- Treat them as collaboration preferences, not as universal facts.\n")
    lines.append("- Follow the user's latest explicit instruction when it conflicts with this context.\n")
    lines.append("- If the task needs facts not present here, inspect the real material or ask for it instead of guessing.\n\n")
    lines.append("## Collaboration Rules\n\n")

    for i, ax in enumerate(axioms, 1):
        statement = ax.get("statement", "(missing)")
        confidence = ax.get("confidence")
        lines.append(f"### {i}. {statement}\n\n")
        if confidence:
            lines.append(f"Confidence: {confidence}\n\n")
        if exec_req := ax.get("执行要求"):
            lines.append(f"How the AI should behave: {exec_req}\n\n")
        if counter := ax.get("反例"):
            lines.append(f"When not to over-apply it: {counter}\n\n")

    return "".join(lines)


def build_evidence_md(profile: dict) -> str:
    """Build an audit appendix with refs that should not be pasted by default."""
    axioms = profile.get("axioms", [])
    lines: list[str] = []
    lines.append("# Profile Evidence Appendix\n\n")
    lines.append("This file is for auditing traceability. It is not needed for normal AI context loading.\n\n")
    lines.append(f"- Generated: {datetime.now().isoformat(timespec='seconds')}\n")
    lines.append(f"- Generated by: {profile.get('generated_by', 'unknown')}\n")
    lines.append(f"- Schema: {profile.get('version', '?')}\n")
    if source_stats := profile.get("source_stats"):
        lines.append(f"- Source stats: {source_stats}\n")
    lines.append("\n")

    for i, ax in enumerate(axioms, 1):
        conf = ax.get("confidence", "?")
        badge = CONF_BADGE.get(conf, conf)
        lines.append(f"## {i}. {ax.get('statement', '(missing)')}\n\n")
        lines.append(f"- Confidence: {badge}\n")
        refs = ax.get("evidence_refs", [])
        lines.append(f"- Evidence refs: {len(refs)}\n\n")
        for ref in refs:
            lines.append(f"  - `{ref}`\n")
        lines.append("\n")

    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render profile.json to profile.md and personal-context-skill/.")
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path.home() / ".pls-remember-me" / "out")
    args = parser.parse_args()

    profile = json.loads(args.profile.read_text(encoding="utf-8"))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    run_id = datetime.now().strftime("%Y-%m-%d-%H%M%S")
    out_path = args.out_dir / f"{run_id}-profile.md"
    evidence_path = args.out_dir / f"{run_id}-profile-evidence.md"
    skill_dir = args.out_dir / "personal-context-skill"
    skill_path = skill_dir / "SKILL.md"
    skill_context_path = skill_dir / "context-profile.md"

    rendered_profile = build_profile_md(profile)
    rendered_evidence = build_evidence_md(profile)
    out_path.write_text(rendered_profile, encoding="utf-8")
    evidence_path.write_text(rendered_evidence, encoding="utf-8")

    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_context_path.write_text(rendered_profile, encoding="utf-8")
    skill_path.write_text(
        """---
name: personal-context
description: Use when starting work with this user, making product or engineering judgments for them, drafting plans, reviewing AI outputs, or deciding how to collaborate. Applies the user's distilled judgment principles, collaboration preferences, and evidence-backed working rules.
---

# Personal Context

Use this skill to adapt to this user's working style and judgment principles.

## Load First

Read `context-profile.md` in this skill directory before starting the task.

## Operating Rules

1. Treat `context-profile.md` as user-specific collaboration context, not generic advice.
2. Apply the axioms when deciding how to plan, answer, review, or implement.
3. Preserve the evidence-backed boundaries in the profile; do not invent missing identity, domain, or preference facts.
4. If the current task conflicts with an axiom, follow the latest explicit user instruction and note the conflict only when it affects the work.
5. If the profile is stale or insufficient for the task, say what is missing instead of guessing.

## Output Style

- Be concrete and task-focused.
- Prefer evidence, actual files, logs, commands, or source material over plausible inference.
- Keep explanations proportional to the user's request.
""",
        encoding="utf-8",
    )
    print(f"profile_md={out_path}")
    print(f"evidence_md={evidence_path}")
    print(f"skill_dir={skill_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
